name: CI/CD Master
on: 
  push:
    branches:
    - master      # Eventos de Push sobre el branch 'master'
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.201' # Versión del SDK.
    - run: dotnet build --configuration Release
  deployHeroku:
    name: Deploy Heroku
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: login
      uses: actions/heroku@master
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
      with:
        args: container:login
    - name: dotnet publish
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.201' # SDK Version to use.
    - name: build release
      run:  dotnet publish -o app
      
    - name: Create symbolic link DockerFile
      run: ln -s InstagramComputerVision/Dockerfile Dockerfile
      
    - name: herokuPush
      uses: actions/heroku@master
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
      with:
        args: container:push -a instagramcognitiveservice web
    - name: herokuRelease
      uses: actions/heroku@master
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
      with:
        args: container:release -a instagramcognitiveservice web
